### ISSUE TITLE
Add type annotations and docstrings

### ISSUE THREAD

**Issue by r-matsuzaka** [enakai00/colab_rlbook#2]
There are no type annotations and docstrings.
So it is hard for me to read codes.
Is is okay to add them?

**Comment by enakai00** [comment]
I appreciate your proposal. However, as this repo contains codes for a published book, we need to keep the consistency with the descriptions / citations in the book. So we cannot make modifications other than simple bug fixes. (Of course, it's ok for you to fork the repo, as a public repo, and add your own modifications to it.)
